spring.application.name=task-api
spring.profiles.active=dev 

# General architecture settings
spring.jpa.open-in-view=false
server.error.include-message=always
spring.datasource.driver-class-name=org.postgresql.Driver