spring.application.name=task-api

#Active profile which affect the impl ref : @Profile("prod")
spring.profiles.active=prod

#db connection is open till service method starts and ends
spring.jpa.open-in-view=false

#Error message sent to client will have what we are giving in exception
server.error.include-message=always

## Enable the web console
#spring.h2.console.enabled=true
#
## Give your database a fixed, predictable name (instead of a random string)
#spring.datasource.url=jdbc:h2:mem:taskdb

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect